version: "3.8"

services:
  backend:
    build:
      context: . # Root context
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: . # Root context
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    restart: unless-stopped
